CREATE TABLE IF NOT EXISTS tbl_Environment (
  EnvKey VARCHAR(255) NOT NULL,
  EnvValue TEXT,
  Created_On TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Updated_On TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (EnvKey)
);
